=== Drewol/unnamed-sdvx-clone/bin/skins/skin_schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/USCSkinDefinition",
    "definitions": {
        "USCSkinDefinition": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "$schema": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "author": {
                    "type": "string"
                },
                "version": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "minLength": 1,
                    "maxLength": 3
                },
                "game_version": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    },
                    "minLength": 1,
                    "maxLength": 3
                },
                "settings": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/SettingDefinition"
                    }
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "enum": [
                            "http",
                            "file",
                            "sys"
                        ]
                    },
                    "uniqueItems": true
                },
                "website": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                }
            },
            "required": [
                "author",
                "settings",
                "game_version",
                "name",
                "permissions",
                "version",
                "website"
            ],
            "title": "USC Skin Definition"
        },
        "SettingDefinition": {
            "oneOf": [
                {
                    "type": "object",
                    "description": "Separator",
                    "properties": {},
                    "additionalProperties": false
                },
                {
                    "type": "string",
                    "description": "Label"
                },
                {
                    "type": "object",
                    "additionalProperties": false,
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "type": {
                            "const": "integer"
                        },
                        "label": {
                            "type": "string"
                        },
                        "default": {
                            "type": "integer"
                        },
                        "max": {
                            "type": "integer"
                        },
                        "min": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "name",
                        "default",
                        "label",
                        "max",
                        "min",
                        "type"
                    ],
                    "description": "Int definition"
                },
                {
                    "type": "object",
                    "additionalProperties": false,
                    "description": "float definition",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string",
                            "const": "float"
                        },
                        "label": {
                            "type": "string"
                        },
                        "default": {
                            "type": "number"
                        },
                        "max": {
                            "type": "number"
                        },
                        "min": {
                            "type": "number"
                        }
                    },
                    "required": [
                        "name",
                        "default",
                        "label",
                        "max",
                        "min",
                        "type"
                    ]
                },
                {
                    "type": "object",
                    "additionalProperties": false,
                    "description": "boolean definition",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string",
                            "const": "bool"
                        },
                        "label": {
                            "type": "string"
                        },
                        "default": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "name",
                        "default",
                        "label",
                        "type"
                    ]
                },
                {
                    "type": "object",
                    "additionalProperties": false,
                    "description": "text definition",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string",
                            "const": "text"
                        },
                        "label": {
                            "type": "string"
                        },
                        "default": {
                            "type": "string"
                        },
                        "secret": {
                            "type": "boolean",
                            "default": false
                        }
                    },
                    "required": [
                        "name",
                        "default",
                        "label",
                        "type"
                    ]
                },
                {
                    "type": "object",
                    "additionalProperties": false,
                    "description": "color definition",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string",
                            "const": "color"
                        },
                        "label": {
                            "type": "string"
                        },
                        "default": {
                            "type": "string",
                            "pattern": "^[a-f,A-F,0-9]{8}$"
                        }
                    },
                    "required": [
                        "name",
                        "default",
                        "label",
                        "type"
                    ]
                },
                {
                    "type": "object",
                    "additionalProperties": false,
                    "description": "color definition",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "type": {
                            "type": "string",
                            "const": "selection"
                        },
                        "label": {
                            "type": "string"
                        },
                        "default": {
                            "type": "string"
                        },
                        "values": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            },
                            "minLength": 1,
                            "uniqueItems": true
                        }
                    },
                    "required": [
                        "name",
                        "default",
                        "label",
                        "type",
                        "values"
                    ]
                }
            ]
        }
    }
}

=== Drewol/unnamed-sdvx-clone/bin/skins/Default/skin.json
{
    "$schema": "../skin_schema.json",
    "author": "Drewol",
    "game_version": [
        0,
        4,
        0
    ],
    "name": "Default",
    "permissions": [
        "file"
    ],
    "settings": [
        "Gameplay",
        {
            "name": "earlate_position",
            "type": "selection",
            "label": "Early/Late display position",
            "default": "bottom",
            "values": [
                "bottom",
                "middle",
                "top",
                "off"
            ]
        },
        {
            "name": "nick",
            "type": "text",
            "label": "Display name",
            "default": "Guest"
        },
        {},
        "Song select",
        {
            "name": "show_guide",
            "label": "Show control guide on song select",
            "type": "bool",
            "default": true
        },
        {},
        "Result",
        {
            "name": "show_result_hiscore",
            "label": "Show hiscore on result",
            "type": "bool",
            "default": true
        },
        {
            "name": "hit_graph_delta_scale",
            "label": "Hit graph scale (y-axis)",
            "type": "float",
            "default": 0.8,
            "max": 3.0,
            "min": 0.5
        },
        {
            "name": "show_result_guide",
            "label": "Show control guide on result",
            "type": "bool",
            "default": true
        },
        {
            "name": "show_detailed_results",
            "label": "Show detailed results by default",
            "type": "bool",
            "default": false
        },
        {
            "name": "show_result_icons",
            "label": "Show icons related to play settings at the bottom",
            "type": "bool",
            "default": true
        },
        {
            "name": "ir_or_hiscore",
            "label": "Show IR by default in place of hiscore",
            "type": "bool",
            "default": false
        },
        {},
        "Test objects",
        {
            "name": "Testing with space",
            "type": "float",
            "label": "Test setting with spaces in the key",
            "default": 50.0,
            "max": 100.0,
            "min": -100.0
        },
        {
            "name": "Ineger_test",
            "type": "integer",
            "label": "Integer Test with range -100<->100",
            "default": 50,
            "max": 100,
            "min": -100
        },
        {
            "name": "col_test",
            "type": "color",
            "label": "Color Test",
            "default": "007FFFFF"
        },
        {
            "name": "secret_value",
            "type": "text",
            "label": "Secret value test",
            "default": "usc123",
            "secret": true
        }
    ],
    "version": [
        0,
        4
    ],
    "website": "https://github.com/Drewol/unnamed-sdvx-clone"
}
